# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: "Burner Sports"
description: Nützliches, Nutzloses, Interessantes und Belangloses aus meinen Sportaktivitäten, Ernährung, meiner Lebensphilosopie und dem ganzen Rest
url: "http://sports.weinbrenner.name"
twitter_username: weinbrenner
default_img: https://pbs.twimg.com/profile_images/721873175/jwavatar.png

# Profile settings
name:
profile_img: 
profile:
social:
  github:

# Build settings
include: ["_categories"]
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
